### ISSUE TITLE
Some dead links on the JCEL Homepage (http://julianmendez.github.io/jcel/)

### ISSUE THREAD

**Issue by progirep** [julianmendez/jcel#4]
The homepage of JCEL currently has some links that don't lead to the right places. 

In the "Example" section, there are some links to OWL and KRSS file downloads, which are redirected to https://tu-dresden.de/ing/informatik/thi/lat/forschung/software - Clicking on JCEL there leads to http://julianmendez.github.io/jcel/ again.

**Comment by julianmendez** [comment]
Thank you very much for pointing this out. The links are now fixed.
